### PR TITLE
Adding reserved word check to FromDataFrameNetwork

### PR DESCRIPTION
**Pull request by wkumler**
Hi, I didn't pay attention to the "reserved words" list in data.tree when trying to convert from a dataframe (network format) to a data.tree and spent *way* too long trying to debug it. This pull request adds a check for words in the reserved list and warns if that's the case. I just implemented the already-existing `CheckNameReservedWord` from `FromDataFrameTable` with a single line of code, but added some unit tests to ensure it behaves as expected. Happy to respond if others have thoughts.

### CODE REVIEW

**Comment by gluc** [comment]
Hi, thx for this, sounds very reasonable. Did you have a chance to look at why the builds are failing?
FYI, I'm planning a release for in June or July. And it would be great if I could include your Pull Request.

**Comment by wkumler** [comment]
Yeah, sorry - laziness on my part was hoping it was just my local build that was having problems due to some uninstalled packages but it wasn't. The latest commit should fix that - apparently, it's fine if the first two columns are named using a reserved word but none of the others can be. I had named one of those first two with the reserved word to check that the new code throws a warning and it wasn't, thus the failed test. Now the test data frame has the "value" column named "name", which correctly throws the error and passes all checks on my machine. Here's to hoping that it also passes CI!

**Comment by wkumler** [comment]
Looks like it's passing the important ones now - still failing on the dev branch with mingw_32, but I don't think that's connected to my PR: instead, it fails because it can't find the `utf-8` or `data.table` packages.

**Comment by gluc** [comment]
Great, thx a lot. Merged into dev, as I use git flow.

**Pull request merged**
